CREATE TYPE public.report_status_enum AS ENUM (
    'pending',
    'confirmed'
);

CREATE TYPE public.role_enum AS ENUM (
    'admin',
    'user',
    'moderator'
);

CREATE TYPE public.role_type AS ENUM (
    'admin',
    'user'
);

CREATE TYPE public.vote_enum AS ENUM (
    'upvote',
    'downvote'
);

CREATE FUNCTION public.update_comment_score() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
	IF(TG_OP = 'INSERT') THEN
		IF NEW.vote_type = 'UPVOTE' THEN
			UPDATE comments
			SET upvotes = upvotes + 1,
			score = (upvotes + 1) - downvotes
			WHERE comment_id= NEW.comment_id;
		ELSIF NEW.vote_type = 'DOWNVOTE' THEN
			UPDATE comments
			SET downvotes = downvotes + 1,
			score = upvotes - (downvotes + 1)
			WHERE comment_id = NEW.comment_id;
		END IF;
		RETURN NEW;

	ELSIF(TG_OP = 'UPDATE') THEN
		IF OLD.vote_type = 'UPVOTE' AND NEW.vote_type = 'DOWNVOTE' THEN
			UPDATE comments
			SET upvotes = upvotes - 1,
			downvotes = downvotes + 1,
			score = (upvotes -1) - (downvotes + 1)
			WHERE comment_id = NEW.comment_id;
		ELSIF OLD.vote_type = 'DOWNVOTE' AND NEW.vote_type = 'UPVOTE' THEN
			UPDATE comments
			SET downvotes = downvotes - 1,
			upvotes = upvotes + 1,
			score = (upvotes +1) - (downvotes - 1)
			WHERE comment_id = NEW.comment_id;
		END IF;
        RETURN NEW;

	ELSIF (TG_OP = 'DELETE') THEN
        IF OLD.vote_type = 'UPVOTE' THEN
            UPDATE comments 
            SET upvotes = upvotes - 1, score = (upvotes - 1) - downvotes 
            WHERE comment_id = OLD.comment_id;
        ELSIF OLD.vote_type = 'DOWNVOTE' THEN
            UPDATE comments 
            SET downvotes = downvotes - 1, score = upvotes - (downvotes - 1) 
            WHERE comment_id = OLD.comment_id;
        END IF;
        RETURN OLD;
    END IF;
	
	RETURN NULL;

END;
$$;

CREATE TABLE public.backup_codes (
    id bigint NOT NULL,
    code_hash character varying(255) NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.backup_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.backup_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.categories (
    category_id bigint NOT NULL,
    category_name character varying(255) NOT NULL,
    description character varying(255),
    updated_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    is_deleted boolean DEFAULT false NOT NULL
);

ALTER TABLE public.categories ALTER COLUMN category_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.categories_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.chat_participant (
    added_by bigint,
    created_at timestamp(6) without time zone,
    deleted_by bigint,
    is_archived boolean NOT NULL,
    is_deleted boolean,
    is_muted boolean NOT NULL,
    is_pinned boolean NOT NULL,
    last_read_message_id bigint,
    role character varying(255) NOT NULL,
    unread_count integer,
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT chat_participant_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MEMBER'::character varying])::text[])))
);

CREATE TABLE public.chats (
    id bigint NOT NULL,
    chat_avatar_url character varying(255),
    chat_name character varying(100),
    created_at timestamp(6) without time zone,
    is_deleted boolean,
    is_group boolean,
    last_message_at timestamp(6) without time zone,
    last_message_content character varying(2000),
    last_message_id bigint,
    last_message_type character varying(255),
    last_sender_name character varying(255),
    CONSTRAINT chats_last_message_type_check CHECK (((last_message_type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying, 'VOICE'::character varying, 'FILE'::character varying, 'VIDEO'::character varying, 'SYSTEM'::character varying])::text[])))
);

ALTER TABLE public.chats ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chats_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.comment_votes (
    id bigint NOT NULL,
    comment_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    vote_type character varying(255) NOT NULL,
    CONSTRAINT comment_votes_vote_type_check CHECK (((vote_type)::text = ANY ((ARRAY['UPVOTE'::character varying, 'DOWNVOTE'::character varying, 'NONE'::character varying])::text[])))
);

ALTER TABLE public.comment_votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comment_votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.comments (
    comment_id bigint NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    comment_path character varying(255) NOT NULL,
    comment_content text,
    likes bigint DEFAULT 0,
    is_deleted boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone,
    parent_id bigint,
    downvotes bigint DEFAULT 0 NOT NULL,
    score bigint DEFAULT 0 NOT NULL,
    upvotes bigint DEFAULT 0 NOT NULL
);

ALTER TABLE public.comments ALTER COLUMN comment_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.comments_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.follow (
    followed_at timestamp(6) without time zone NOT NULL,
    follower_id bigint NOT NULL,
    following_id bigint NOT NULL
);

CREATE TABLE public.messages (
    id bigint NOT NULL,
    content text,
    is_deleted boolean NOT NULL,
    is_edited boolean NOT NULL,
    reply_to_message_id bigint,
    send_at timestamp(6) without time zone,
    type character varying(255),
    updated_at timestamp(6) without time zone,
    chat_id bigint NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT messages_type_check CHECK (((type)::text = ANY ((ARRAY['TEXT'::character varying, 'IMAGE'::character varying, 'VOICE'::character varying, 'FILE'::character varying, 'VIDEO'::character varying, 'SYSTEM'::character varying])::text[])))
);

ALTER TABLE public.messages ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.messages_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.notification (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_archived boolean NOT NULL,
    is_read boolean NOT NULL,
    read_at timestamp(6) without time zone,
    event_id bigint NOT NULL,
    user_id bigint NOT NULL
);

CREATE TABLE public.notification_event (
    event_id bigint NOT NULL,
    date_notice timestamp(6) without time zone NOT NULL,
    description text,
    event_name character varying(100) NOT NULL,
    event_type character varying(255),
    created_by bigint NOT NULL,
    reference_id bigint,
    reference_type character varying(255),
    metadata text,
    target_url character varying(255)
);

ALTER TABLE public.notification_event ALTER COLUMN event_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_event_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE public.notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.pinnedpost (
    pinned_post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

CREATE TABLE public.post_categories (
    post_id bigint NOT NULL,
    category_id bigint NOT NULL
);

CREATE TABLE public.post_collection (
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    post_id bigint NOT NULL,
    collection_id bigint NOT NULL
);

CREATE TABLE public.post_entity (
    post_id bigint NOT NULL,
    counted_views bigint,
    created_at timestamp(6) without time zone,
    downvotes bigint,
    is_deleted boolean,
    post_content text,
    thumbnail character varying(255),
    updated_at timestamp(6) without time zone,
    upvotes bigint,
    creator_id bigint NOT NULL,
    post_title character varying(255),
    is_archived boolean,
    status character varying(255),
    comment_count integer,
    summary text,
    CONSTRAINT post_entity_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PUBLISHED'::character varying, 'ARCHIVED'::character varying])::text[])))
);

ALTER TABLE public.post_entity ALTER COLUMN post_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_entity_post_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_media (
    id bigint NOT NULL,
    media_type character varying(255),
    size bigint,
    url character varying(255),
    post_id bigint,
    public_id character varying(255),
    format character varying(255),
    CONSTRAINT post_media_media_type_check CHECK (((media_type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying, 'FILE'::character varying])::text[])))
);

ALTER TABLE public.post_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.post_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.post_tags (
    post_id bigint NOT NULL,
    tag_id bigint NOT NULL
);

CREATE TABLE public.reports (
    id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    post_id bigint,
    comment_id bigint,
    user_id bigint NOT NULL,
    reason bigint NOT NULL,
    status public.report_status_enum DEFAULT 'pending'::public.report_status_enum,
    processed_by bigint,
    CONSTRAINT reports_check_post_or_comment CHECK ((((post_id IS NOT NULL) AND (comment_id IS NULL)) OR ((post_id IS NULL) AND (comment_id IS NOT NULL))))
);

ALTER TABLE public.reports ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.reports_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.roles (
    role_id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.roles ALTER COLUMN role_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_role_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.save_collection (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_deleted boolean NOT NULL,
    name character varying(255),
    thumbnail_url character varying(255),
    total_elements bigint,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);

ALTER TABLE public.save_collection ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.save_collection_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.save_posts (
    save_id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.save_posts ALTER COLUMN save_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.save_posts_save_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.tags (
    tag_id bigint NOT NULL,
    tag_name character varying(255) NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.tags ALTER COLUMN tag_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.tags_tag_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_devices (
    id bigint NOT NULL,
    device_id character varying(255),
    device_name character varying(255),
    expires_at timestamp(6) with time zone,
    last_active_at timestamp(6) with time zone,
    last_ip character varying(255),
    refresh_token_hash character varying(255),
    status character varying(255),
    user_id bigint,
    CONSTRAINT user_devices_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'REVOKED'::character varying, 'EXPIRED'::character varying])::text[])))
);

ALTER TABLE public.user_devices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_devices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_favorite_categories (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    category_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);

ALTER TABLE public.user_favorite_categories ALTER COLUMN id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.user_favorite_categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.user_roles (
    user_id bigint NOT NULL,
    role_id bigint NOT NULL
);

CREATE TABLE public.user_verification_token (
    id bigint NOT NULL,
    expired_date timestamp(6) without time zone,
    token character varying(255),
    user_id bigint NOT NULL,
    send_time timestamp(6) without time zone,
    sent_count integer DEFAULT 0 NOT NULL
);

ALTER TABLE public.user_verification_token ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_verification_token_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    user_id bigint NOT NULL,
    email character varying(255) NOT NULL,
    user_password character varying(255),
    user_name character varying(255) NOT NULL,
    avatar_url character varying(255) DEFAULT 'https://cdn-icons-png.flaticon.com/512/9815/9815472.png'::character varying,
    is_deleted boolean DEFAULT false,
    is_verified boolean DEFAULT false,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone,
    provider character varying(255),
    provider_id character varying(255),
    bio character varying(255),
    slug character varying(255),
    is_2fa_enabled boolean,
    two_factor_secret character varying(255),
    CONSTRAINT users_user_name_check CHECK ((char_length((user_name)::text) >= 6)),
    CONSTRAINT users_user_password_check CHECK ((char_length((user_password)::text) >= 6))
);

ALTER TABLE public.users ALTER COLUMN user_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.users_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.votes (
    id bigint NOT NULL,
    post_id bigint NOT NULL,
    user_id bigint NOT NULL,
    vote_type character varying(255),
    created_at timestamp(6) without time zone,
    CONSTRAINT votes_vote_type_check CHECK (((vote_type)::text = ANY ((ARRAY['UPVOTE'::character varying, 'DOWNVOTE'::character varying, 'NONE'::character varying])::text[])))
);

ALTER TABLE public.votes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.votes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.backup_codes
    ADD CONSTRAINT backup_codes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_category_name_key UNIQUE (category_name);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (category_id);

ALTER TABLE ONLY public.chat_participant
    ADD CONSTRAINT chat_participant_pkey PRIMARY KEY (chat_id, user_id);

ALTER TABLE ONLY public.chats
    ADD CONSTRAINT chats_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comment_votes
    ADD CONSTRAINT comment_votes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_pkey PRIMARY KEY (comment_id);

ALTER TABLE ONLY public.follow
    ADD CONSTRAINT follow_pkey PRIMARY KEY (follower_id, following_id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT messages_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.notification_event
    ADD CONSTRAINT notification_event_pkey PRIMARY KEY (event_id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT notification_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.pinnedpost
    ADD CONSTRAINT pinnedpost_pinned_post_id_key UNIQUE (pinned_post_id);

ALTER TABLE ONLY public.pinnedpost
    ADD CONSTRAINT pinnedpost_pkey PRIMARY KEY (pinned_post_id, user_id);

ALTER TABLE ONLY public.post_categories
    ADD CONSTRAINT post_categories_pkey PRIMARY KEY (post_id, category_id);

ALTER TABLE ONLY public.post_collection
    ADD CONSTRAINT post_collection_pkey PRIMARY KEY (collection_id, post_id);

ALTER TABLE ONLY public.post_entity
    ADD CONSTRAINT post_entity_pkey PRIMARY KEY (post_id);

ALTER TABLE ONLY public.post_media
    ADD CONSTRAINT post_media_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT post_tags_pkey PRIMARY KEY (post_id, tag_id);

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (role_id);

ALTER TABLE ONLY public.save_collection
    ADD CONSTRAINT save_collection_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.save_posts
    ADD CONSTRAINT save_posts_pkey PRIMARY KEY (save_id);

ALTER TABLE ONLY public.tags
    ADD CONSTRAINT tags_pkey PRIMARY KEY (tag_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk82kvqupf9ax45leg8b0nofwh2 UNIQUE (slug);

ALTER TABLE ONLY public.user_verification_token
    ADD CONSTRAINT uk98w5gv79qjmhs4xxfxwomqsok UNIQUE (user_id);

ALTER TABLE ONLY public.save_posts
    ADD CONSTRAINT uk9n9hbyaqyaotcjky09ktue76b UNIQUE (user_id, post_id);

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT ukofx66keruapi6vyqpv6f2or37 UNIQUE (name);

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT ukpa0qu72klq223r3f3mpgf9ele UNIQUE (user_id, post_id);

ALTER TABLE ONLY public.comment_votes
    ADD CONSTRAINT ukvffcdpe6xmdagi3lxch43hjb UNIQUE (comment_id, user_id);

ALTER TABLE ONLY public.user_devices
    ADD CONSTRAINT user_devices_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_favorite_categories
    ADD CONSTRAINT user_favorite_categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.user_favorite_categories
    ADD CONSTRAINT user_favorite_categories_user_id_category_id_key UNIQUE (user_id, category_id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id);

ALTER TABLE ONLY public.user_verification_token
    ADD CONSTRAINT user_verification_token_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (user_id);

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT votes_pkey PRIMARY KEY (id);

CREATE INDEX idx_chat_send_at ON public.messages USING btree (chat_id, send_at);

CREATE TRIGGER trigger_update_comment_score AFTER INSERT OR DELETE OR UPDATE ON public.comment_votes FOR EACH ROW EXECUTE FUNCTION public.update_comment_score();

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT comments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.post_categories
    ADD CONSTRAINT fk3nrfo4vtbrgjb8n4bsmpiy4o1 FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id);

ALTER TABLE ONLY public.post_media
    ADD CONSTRAINT fk4ntyl7nuj48ynu1rtertyveoq FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id);

ALTER TABLE ONLY public.backup_codes
    ADD CONSTRAINT fk4uqupj7j6eldpff5ycw8vnpm6 FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fk64w44ngcpqp99ptcb9werdfmb FOREIGN KEY (chat_id) REFERENCES public.chats(id);

ALTER TABLE ONLY public.chat_participant
    ADD CONSTRAINT fk6fajes8610anpxk08rqftw03k FOREIGN KEY (chat_id) REFERENCES public.chats(id);

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT fk7eltugh9gt12rfvmsjpegbqce FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id);

ALTER TABLE ONLY public.follow
    ADD CONSTRAINT fk9oqsjovu9bl95dwt8ibiy2oey FOREIGN KEY (following_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.user_verification_token
    ADD CONSTRAINT fk9qrpqu5pxa02qkrrs5x2l5p1e FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.post_categories
    ADD CONSTRAINT fkb4lve46iv2mn28s6sflk8iksn FOREIGN KEY (category_id) REFERENCES public.categories(category_id);

ALTER TABLE ONLY public.save_posts
    ADD CONSTRAINT fkdiktr1tuwe83h2tcsgic5f6by FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.chat_participant
    ADD CONSTRAINT fke2s50kw19y5jwfi23jl5v6ov7 FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT fkesi4dmem2vt154415b835ufv1 FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id);

ALTER TABLE ONLY public.save_collection
    ADD CONSTRAINT fkf3uqncb7uvvsflmp2uxqttj0g FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fkgruhi9u0nwfbhl7cmrhjwscle FOREIGN KEY (event_id) REFERENCES public.notification_event(event_id);

ALTER TABLE ONLY public.post_collection
    ADD CONSTRAINT fkgv7x6c3l4kh8unld28ke51hq3 FOREIGN KEY (collection_id) REFERENCES public.save_collection(id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkh8ciramu9cc9q3qcqiv4ue8a6 FOREIGN KEY (role_id) REFERENCES public.roles(role_id);

ALTER TABLE ONLY public.user_roles
    ADD CONSTRAINT fkhfh9dx7w3ubf1co1vdev94g3f FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.follow
    ADD CONSTRAINT fkjikg34txcxnhcky26w14fvfcc FOREIGN KEY (follower_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.votes
    ADD CONSTRAINT fkli4uj3ic2vypf5pialchj925e FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.post_tags
    ADD CONSTRAINT fkm6cfovkyqvu5rlm6ahdx3eavj FOREIGN KEY (tag_id) REFERENCES public.tags(tag_id);

ALTER TABLE ONLY public.notification
    ADD CONSTRAINT fknk4ftb5am9ubmkv1661h15ds9 FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.comments
    ADD CONSTRAINT fkp83v7smymcwnon8sgslhar0e8 FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id);

ALTER TABLE ONLY public.notification_event
    ADD CONSTRAINT fkp892x24wdacc1w97trkklbtkv FOREIGN KEY (created_by) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.messages
    ADD CONSTRAINT fkpsmh6clh3csorw43eaodlqvkn FOREIGN KEY (user_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.post_collection
    ADD CONSTRAINT fkqggw061kt74a3isn3b09y13m0 FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id);

ALTER TABLE ONLY public.save_posts
    ADD CONSTRAINT fkqoehqek8yq57pp7nl6dbn0grw FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id);

ALTER TABLE ONLY public.post_entity
    ADD CONSTRAINT fks0u6t8logqed64lfjr5bdjgwf FOREIGN KEY (creator_id) REFERENCES public.users(user_id);

ALTER TABLE ONLY public.pinnedpost
    ADD CONSTRAINT pinnedpost_pinned_post_id_fkey FOREIGN KEY (pinned_post_id) REFERENCES public.post_entity(post_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.pinnedpost
    ADD CONSTRAINT pinnedpost_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_post_id_fkey FOREIGN KEY (post_id) REFERENCES public.post_entity(post_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_processed_by_fkey FOREIGN KEY (processed_by) REFERENCES public.users(user_id) ON DELETE SET NULL;

ALTER TABLE ONLY public.reports
    ADD CONSTRAINT reports_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_favorite_categories
    ADD CONSTRAINT user_favorite_categories_category_id_fkey FOREIGN KEY (category_id) REFERENCES public.categories(category_id) ON DELETE CASCADE;

ALTER TABLE ONLY public.user_favorite_categories
    ADD CONSTRAINT user_favorite_categories_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(user_id) ON DELETE CASCADE;

